apiVersion: v1
kind: Service
metadata:
  name: cloud-discovery
  labels:
    run: cloud-discovery
spec:
  ports:
  - port: 9083
    targetPort: 9083
    protocol: TCP
  selector:
    run: cloud-discovery
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-discovery
  labels:
    app: cloud-discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-discovery
  template:
    metadata:
      labels:
        app: cloud-discovery
    spec:
      containers:
      - name: cloud-discovery
        image: docker.io/twistlock/cloud-discovery:latest
        ports:
        - containerPort: 9083